name: main action

on:
  push:
    branches:
      - main
      - develop/*

jobs:
  initialize:
    name: Initialize data
    runs-on: ubuntu-latest
    steps:
      - name: Print a opening
        env:
          MY_VAR: Hi there! Initializing data!
        run: |
          echo $MY_VAR
